apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 266735804784.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app-repo:v1.0.12
          env:
            - name: APPLICATION_NAME
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: APPLICATION_NAME
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: DB_PASSWORD
            - name: DB_CLASSNAME
            
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: DB_CLASSNAME
            - name: AWS_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: AWS_S3_ACCESS_KEY
            - name: AWS_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: AWS_S3_SECRET_KEY
            - name: AWS_REGION_STATIC
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: AWS_REGION_STATIC
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: S3_BUCKET
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: SPRING_REDIS_PORT
              
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: JWT_SECRET
            - name: KAKAO_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: KAKAO_ADMIN_KEY
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: spring-env-secret
                  key: KAKAO_REDIRECT_URI        
            
          ports:
            - containerPort: 8080
